## 特征值分解
### 1. Av = λv
- v是A的特征向量, λ是一个特征值

### 2. 求矩阵的特征值
- 根据 A - λI的行列式等于0, 可以求解 到特征值

### 3. 求矩阵的每个特征值对应的特征向量
- 根据 Av = λv, 可以求解特征向量

### 4. 分解矩阵
- A = W∑W^(-1)

### 5. 性质:
- 连续的A相乘: pow(A, n) = W pow(∑, n) pow(W, -1)
- A的逆矩阵: pow(A, -1) = W pow(∑, -1), pow(W, -1)
- A的行列式: det(A) = Πλ, 特征值的累积

### 6. 其他分解
- the Jordan Normal Form
- Singlar value decomposition

### 7. Gershgorin Circle Theorem
- 对于对称矩阵, 有办法可以获取每个特征值的范围: 
    - Raius[i] = Sum(A[i, :])
    - A[i][i] - Radius[i] <= lambda[i] <= A[i][i] + Radius[i]

In [3]:
from IPython import display
import numpy as np
from numpy import linalg
%matplotlib inline

In [7]:
# 找特征值
A = np.array([[2, 1], [2, 3]])
eigen_values, eigen_vectors = linalg.eig(A)
print(eigen_values)
print(eigen_vectors)

[1. 4.]
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [10]:
np.set_printoptions(suppress=True)

In [11]:
m_1 = np.array([[2,1], [1,2]])
m_2 = np.array([[2,1], [0,2]])
print(linalg.eig(m_1))

(array([3., 1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [12]:
linalg.eig(m_2)  # 只有一个特征值

(array([2., 2.]), array([[ 1., -1.],
        [ 0.,  0.]]))

In [14]:
# 试试奇异值分解
example = np.array([[1,0], [1,1], [0,1]])
U = example.dot(example.T) 
print(U)
V = example.T.dot(example)
print(V)
Sigma = linalg.eigvals(V)
print(Sigma)

[[1 1 0]
 [1 2 1]
 [0 1 1]]
[[2 1]
 [1 2]]
[3. 1.]


In [17]:
U = linalg.eig(U)[1]

In [18]:
V = linalg.eig(V)[1]

In [24]:
Sigma = np.sqrt(np.array([[3,0], [0,1], [0,0]]))
U.dot(Sigma).dot(V.T)

array([[-1.,  0.],
       [-1., -1.],
       [-0., -1.]])

In [22]:
V

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [25]:
pow(2, 0.1)

1.0717734625362931